### ISSUE TITLE
Make the bubble generic

### ISSUE THREAD

**Issue by ilusi0n** [vanshg395/bubble_timeline#1]
Hey!

I liked your package very much and kinda suits my needs.
The only thing that I wanted was to show a circular image instead of an icon. What do you think if instead of passing an icon, we could pass a widget so it became generic?

Thank you!

**Comment by vanshg395** [comment]
@ilusi0n Thanks for pointing this out!

Well technically you can still pass an Image to the icon parameter because it takes a Widget type child, but I will change the parameter name.

**Comment by vanshg395** [comment]
Fixed and pushed
